name: CI (Darwin)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-14 ]
        toolchain:
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update Rust
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build
        run: |
          # This is a hack: bindgen fails to produce valid output on macOS && GHA.
          # Instead, supply CLAP bindings derived beforehand on a macOS machine:
          cargo build --verbose --package clap-sys
          cd ${{ github.workspace }}
          cp ./.github/assets/bindings_darwin-M1_clap123.rs $(find ./ -iname "bindings.rs")
          cargo build --verbose --workspace
      - name: Test
        run: |
          cargo test --verbose --workspace
      - name: Build/test docs
        run: |
          cargo doc --verbose --workspace
          cargo test --doc --verbose --workspace
