name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04, windows-2022 ]
        toolchain:
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose --workspace
      - name: Test
        run: cargo test --verbose --workspace
      - name: Build/test docs
        run: |
          cargo doc --verbose --workspace
          cargo test --doc --verbose --workspace