name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        profile:
          - dev
          - release
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-2022
          - macos-13
          - macos-14
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Update Rust
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build
        run: |
          cargo build --verbose --profile ${{ matrix.profile }}
      - name: Build examples
        run: |
          cargo build --examples --profile ${{ matrix.profile }}
      - name: Test
        run: |
          cargo test --verbose --profile ${{ matrix.profile }}
